apiVersion: v1
kind: Service
metadata:
  name: shawarma-example
  labels:
    svc: shawarma-example
spec:
  type: LoadBalancer
  selector:
    app: shawarma-example
    active: 'true'
  ports:
  - name: http
    port: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shawarma-example
  labels:
    app: shawarma-example
spec:
  replicas: 2
  selector:
    matchLabels:
      app: shawarma-example
  template:
    metadata:
      labels:
        app: shawarma-example
        active: 'true'
    spec:
      containers:
        - name: primary
          image: btburnett3/shawarma-example:oldstyle-1
          ports:
          - name: http
            containerPort: 80
