apiVersion: v1
kind: Service
metadata:
  name: shawarma-example
  namespace: shawarma-example
  labels:
    svc: shawarma-example
spec:
  selector:
    app: shawarma-example
    active: 'true'
  ports:
  - name: http
    port: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: shawarma-example
  namespace: shawarma-example
  labels:
    app: shawarma-example
    active: 'false'
spec:
  containers:
    - name: primary
      image: btburnett3/shawarma-example:oldstyle-1
      ports:
      - name: http
        containerPort: 80
